FROM python:3.10-slim

WORKDIR /app

RUN apt-get update \
	&& apt-get install -y --no-install-recommends gcc libssl-dev \
	&& rm -rf /var/lib/apt/lists/*

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 5000

ENV FLASK_ENV=development
ENV FLASK_RUN_HOST=0.0.0.0
ENV FLASK_APP=app:create_app

CMD ["python", "-m", "flask", "run"] 