version: "3.9"

services:
  flask:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: flask_app_dev
    ports:
      - "5000:5000"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
